"""
Make the boxplot from data
"""

__version__ = "1.0"
__author__ = "Frederico Moeller"
__copyright__ = "Copyright 2021, Frederico Moeller"
__license__ = "MIT"


import functools
import numpy as np
import pandas as pd
import leitor
import matplotlib.pyplot as plt
from math import inf

pastas = pd.read_csv("pastas.csv")
prblm = pd.read_csv("problemas.csv")

def take_data(prblm, insts):
    """ Extract the data generated by a group of algorithms for a given problem. """

    insts = list(insts)
    if prblm == "cc":
        if 'results/random-population/sam/' in insts:
            insts.remove('results/random-population/sam/')
            return [leitor.captura('results/random-population/sam/','cc')]+list(
                map(leitor.captura,insts,['ccp']*len(insts)))

    #return [leitor.captura(i,prblm) for i in insts]
    return list(map(leitor.captura,insts,[prblm]*len(insts)))

def make_boxplot(prblm, insts, directory = "", extra_name = "", fmt = 'png'):
    """ Make boxplots from the data generated by a group of algotithms for a given problem. """
    algor = insts['Pasta']
    names = insts['algoritmo']
    bplt_val = take_data(prblm, algor)
    for data in bplt_val:
        while None in data:
            data.remove(None)
    fig, ax = plt.subplots()
    ax.boxplot(bplt_val, labels = names)
    ax.set_title(prblm)
    fig1 = plt.gcf()
    fig1.set_size_inches((19, 13), forward=False)
    fig.savefig(directory+'/'+extra_name+'_'+prblm+'.'+fmt,dpi=100, format=fmt)
    #plt.show()

